name: Email Step Workflow

on:
  push:
    branches: [main]  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 24ds3000056@ds.study.iitm.ac.in
        run: echo "Hello from 24ds3000056@ds.study.iitm.ac.in!"
